### PR TITLE
Add the retry script to owncloudci/golang images

### PR DESCRIPTION
**Pull request by phil-davis**
Issue https://github.com/owncloud-ci/retry/issues/7

### CODE REVIEW

**Review by xoxys — APPROVED** [review]
I would recommend to use `-SsfL` otherwise curl will write the returned message to the output file in case of 4xx. Besides that LGTM

**Comment by phil-davis** [comment]
> I would recommend to use `-SsfL` otherwise curl will write the returned message to the output file in case of 4xx.

Done (I copied the code from the `owncloudci/nodejs` Dockerfile.* - so I will add the `f` there also.

**Comment by xoxys** [comment]
This should be the case already https://github.com/owncloud-ci/nodejs/pull/65/files. Maybe not copied from default branch?

**Comment by phil-davis** [comment]
> Maybe not copied from default branch?

Yes, it is correct in the `owncloudci/nodejs` repo. Maybe I copied from the original PR, and that did not have the `f` switch. Anyway, all good.

**Pull request merged**
